//
// Created by brant on 7/3/25.
//
//#define RMKIT_IMPLEMENTATION
//#define STB_IMAGE_IMPLEMENTATION
//#define STB_IMAGE_RESIZE_IMPLEMENTATION
//#define STB_IMAGE_WRITE_IMPLEMENTATION
//#define STB_TRUETYPE_IMPLEMENTATION
//#include <rmkit.h>
